[versions]
buildToolsVersion = "33.0.0"
compileSdkString = "33"
minSdkString = "21"
targetSdkString = "33"

# development
agp = "8.0.2"
kotlin = "1.7.0"

# lib versions
moshi = "1.14.0"
okHttp = "4.10.0"
retrofit = "2.9.0"
mockK = "1.13.5"
junit4 = "4.12"
testRunner = "1.1.1"
androidXTest = "1.1.0"
espresso = "3.1.1"

[libraries]
build-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
build-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

# network
network-moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
network-moshi-core = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
network-moshi-kotlinCodeGen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
network-okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
network-okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }
network-okhttp-mockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okHttp" }
network-retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
network-retrofit-moshiConverter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
network-retrofit-rxJavaAdapter = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "retrofit" }
network-retrofit-scalarsConverter = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }

# unit test
test-junit4 = { module = "junit:junit", version.ref = "junit4" }
test-mockK = { module = "io.mockk:mockk", version.ref = "mockK" }

# android test
androidTest-androidXTest-core = { module = "androidx.test:core", version.ref = "androidXTest" }
androidTest-androidXTest-junit = { module = "androidx.test.ext:junit", version.ref = "androidXTest" }
androidTest-testRunner = { module = "androidx.test:runner", version.ref = "testRunner" }
androidTest-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }