import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
object Libs {
    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * http://tools.android.com */
    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
            Versions.constraintlayout

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html */
    const val lifecycle_compiler: String = "androidx.lifecycle:lifecycle-compiler:" +
            Versions.androidx_lifecycle

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html */
    const val lifecycle_extensions: String = "androidx.lifecycle:lifecycle-extensions:" +
            Versions.androidx_lifecycle

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val lifecycle_viewmodel_ktx: String = "androidx.lifecycle:lifecycle-viewmodel-ktx:" +
            Versions.androidx_lifecycle

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val recyclerview: String = "androidx.recyclerview:recyclerview:" + Versions.recyclerview

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html */
    const val room_compiler: String = "androidx.room:room-compiler:" + Versions.androidx_room

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html */
    const val room_runtime: String = "androidx.room:room-runtime:" + Versions.androidx_room

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html */
    const val room_rxjava2: String = "androidx.room:room-rxjava2:" + Versions.androidx_room

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html */
    const val room_testing: String = "androidx.room:room-testing:" + Versions.androidx_room

    /**
     * https://developer.android.com/testing */
    const val espresso_core: String = "androidx.test.espresso:espresso-core:" +
            Versions.espresso_core

    /**
     * https://developer.android.com/testing */
    const val androidx_test_ext_junit: String = "androidx.test.ext:junit:" +
            Versions.androidx_test_ext_junit

    /**
     * https://developer.android.com/testing */
    const val androidx_test_core: String = "androidx.test:core:" + Versions.androidx_test_core

    /**
     * https://developer.android.com/testing */
    const val androidx_test_runner: String = "androidx.test:runner:" + Versions.androidx_test_runner

    /**
     * https://developer.android.com/studio */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    /**
     * https://developer.android.com/studio */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val material: String = "com.google.android.material:material:" + Versions.material

    /**
     * https://github.com/google/gson */
    const val gson: String = "com.google.code.gson:gson:" + Versions.gson

    /**
     * https://github.com/google/dagger */
    const val dagger_android_processor: String = "com.google.dagger:dagger-android-processor:" +
            Versions.com_google_dagger

    /**
     * https://github.com/google/dagger */
    const val dagger_android_support: String = "com.google.dagger:dagger-android-support:" +
            Versions.com_google_dagger

    /**
     * https://github.com/google/dagger */
    const val dagger_android: String = "com.google.dagger:dagger-android:" +
            Versions.com_google_dagger

    /**
     * https://github.com/google/dagger */
    const val dagger_compiler: String = "com.google.dagger:dagger-compiler:" +
            Versions.com_google_dagger

    /**
     * https://github.com/google/dagger */
    const val dagger: String = "com.google.dagger:dagger:" + Versions.com_google_dagger

    const val retrofit2_rxjava2_adapter: String =
            "com.jakewharton.retrofit:retrofit2-rxjava2-adapter:" +
            Versions.retrofit2_rxjava2_adapter

    const val rxbinding_appcompat: String = "com.jakewharton.rxbinding3:rxbinding-appcompat:" +
            Versions.com_jakewharton_rxbinding3

    const val rxbinding_core: String = "com.jakewharton.rxbinding3:rxbinding-core:" +
            Versions.com_jakewharton_rxbinding3

    const val rxbinding_material: String = "com.jakewharton.rxbinding3:rxbinding-material:" +
            Versions.com_jakewharton_rxbinding3

    const val rxbinding_recyclerview: String =
            "com.jakewharton.rxbinding3:rxbinding-recyclerview:" +
            Versions.com_jakewharton_rxbinding3

    const val rxbinding: String = "com.jakewharton.rxbinding3:rxbinding:" +
            Versions.com_jakewharton_rxbinding3

    const val rxrelay: String = "com.jakewharton.rxrelay2:rxrelay:" + Versions.rxrelay

    /**
     * https://github.com/square/okhttp */
    const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:" +
            Versions.logging_interceptor

    /**
     * https://github.com/square/picasso/ */
    const val picasso: String = "com.squareup.picasso:picasso:" + Versions.picasso

    /**
     * https://github.com/square/retrofit/ */
    const val converter_gson: String = "com.squareup.retrofit2:converter-gson:" +
            Versions.com_squareup_retrofit2

    /**
     * https://github.com/square/retrofit/ */
    const val retrofit: String = "com.squareup.retrofit2:retrofit:" +
            Versions.com_squareup_retrofit2

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    const val arrow_core_data: String = "io.arrow-kt:arrow-core-data:" + Versions.io_arrow_kt

    const val arrow_core_extensions: String = "io.arrow-kt:arrow-core-extensions:" +
            Versions.io_arrow_kt

    const val arrow_effects_data: String = "io.arrow-kt:arrow-effects-data:" + Versions.io_arrow_kt

    const val arrow_effects_extensions: String = "io.arrow-kt:arrow-effects-extensions:" +
            Versions.io_arrow_kt

    const val arrow_extras_data: String = "io.arrow-kt:arrow-extras-data:" + Versions.io_arrow_kt

    const val arrow_extras_extensions: String = "io.arrow-kt:arrow-extras-extensions:" +
            Versions.io_arrow_kt

    const val arrow_syntax: String = "io.arrow-kt:arrow-syntax:" + Versions.io_arrow_kt

    /**
     * https://github.com/arrow-kt/arrow/ */
    const val arrow_typeclasses: String = "io.arrow-kt:arrow-typeclasses:" + Versions.io_arrow_kt

    /**
     * http://mockk.io */
    const val mockk: String = "io.mockk:mockk:" + Versions.mockk

    /**
     * https://github.com/ReactiveX/RxAndroid */
    const val rxandroid: String = "io.reactivex.rxjava2:rxandroid:" + Versions.rxandroid

    /**
     * https://github.com/ReactiveX/RxJava */
    const val rxjava: String = "io.reactivex.rxjava2:rxjava:" + Versions.rxjava

    /**
     * http://junit.org */
    const val junit_junit: String = "junit:junit:" + Versions.junit_junit

    /**
     * http://jacoco.org */
    const val org_jacoco_agent: String = "org.jacoco:org.jacoco.agent:" + Versions.org_jacoco

    /**
     * http://jacoco.org */
    const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:" + Versions.org_jacoco


    const val compose_runtime = "androidx.compose:compose-runtime:${Versions.compose_version}"
    const val compose_compiler = "androidx.compose:compose-compiler:${Versions.compose_version}"

    const val compose_layout = "androidx.ui:ui-layout:${Versions.compose_version}"
    const val compose_core = "androidx.ui:ui-core:${Versions.compose_version}"
    const val compose_android_text = "androidx.ui:ui-android-text:${Versions.compose_version}"
    const val compose_framework = "androidx.ui:ui-framework:${Versions.compose_version}"
    const val compose_tooling = "androidx.ui:ui-tooling:${Versions.compose_version}"
    const val compose_animation = "androidx.ui:ui-animation:${Versions.compose_version}"
    const val compose_material = "androidx.ui:ui-material:${Versions.compose_version}"
    const val compose_text = "androidx.ui:ui-text:${Versions.compose_version}"
}
    /**
     * https://kotlinlang.org/ */
//    const val kotlin_android_extensions_runtime: String =
//            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" +
//            Versions.org_jetbrains_kotlin

    /**
//     * https://kotlinlang.org/ */
//    const val kotlin_android_extensions: String =
//            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
//    const val kotlin_annotation_processing_gradle: String =
//            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" +
//            Versions.org_jetbrains_kotlin
//
//    /**
//     * https://kotlinlang.org/ */
//    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
//            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
//    const val kotlin_stdlib_jdk7: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" +
//            Versions.org_jetbrains_kotlin
//}
