name: 'pr check'

on:
  pull_request:
  push:
    branches:
      - master
      - main
jobs:
  checkout:
    name: 'checkout'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: checkout project
        uses: actions/checkout@v4

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

  checks:
    name: 'checks'
    needs: checkout
    permissions:
      contents: read

    steps:
      - name: "run checks"
        env:
          USERNAME: ${{ secrets.GH_USER_PACKAGE_READ }}
          TOKEN: ${{ secrets.GH_TOKEN_PACKAGE_READ }}
        run: ./gradlew check --no-daemon

  snapshot_test:
    name: 'snapshot test'
    needs: checkout
    permissions:
      contents: read

    steps:
      - name: "run snapshot verification"
        env:
          USERNAME: ${{ secrets.GH_USER_PACKAGE_READ }}
          TOKEN: ${{ secrets.GH_TOKEN_PACKAGE_READ }}
        run: ./gradlew validateDebugScreenshotTest --no-daemon
